services:
  pg1:
    image: oncharterliz/pg-1c-15:latest
    volumes:
      - pg1-data:/var/lib/pgpro/1c-15/data
    ports:
    - "127.0.0.1:5432:5432"
    - "127.0.0.1:8008:8008"
    networks:
      - etcd-net
    environment:
        PATRONI_NAME: pg1
        PATRONI_SCOPE: pg-cluster
        PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"

  pg2:
    image: oncharterliz/pg-1c-15:latest
    volumes:
      - pg2-data:/var/lib/pgpro/1c-15/data
    networks:
      - etcd-net
    environment:
        PATRONI_NAME: pg2
        PATRONI_SCOPE: pg-cluster
        PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"

  psql-client:
    image: postgres:15-alpine
    command: ["sh","-c","sleep infinity"]
    networks:
      - etcd-net

volumes:
  pg1-data:
  pg2-data:

networks:
  etcd-net:
    external: true